### ISSUE TITLE
Set nonce to millisec

### ISSUE THREAD

**Issue by Yuki-Inoue** [bitbankinc/ruby_bitbankcc#6]
In the bitbank official api documentation, on it's demo, epoch in millisec is used for nonce.  In this library, however, for nonce epoch in second is used.

This is inconvenient for the library user, because having millisec in official doc and using seconds in the library makes it impossible for the user to use api key/secret he/she is using on his/her application to simply paste it on the api demo on doc page and see the behavior, as once he/she used the api demo, the nonce increases significantly and he would no longer be able to use that apikey on his application.

So, I think the nonce used in this library should be changed to millisec.

* What do you think about it?
  * If this is sensible, then would you merge PR for this fix if I am to make it?

**Comment by yuma300** [comment]
I appreciate your suggestion.
Since your suggestion is sensible, I will merge your PR.
